export const GET_ALCOHOLIC_INGREDIENTS = "GET_ALCOHOLIC_INGREDIENTS";
export const GET_ALCOHOLIC_INGREDIENTS_FAIL = "GET_ALCOHOLIC_INGREDIENTS_FAIL";
export const GET_CURRENTLY_SELECTED = "GET_CURRENTLY_SELECTED";
export const GET_CURRENTLY_SELECTED_FAIL = "GET_CURRENTLY_SELECTED_FAIL";
export const RESET_CURRENTLY_SELECTED = "RESET_CURRENTLY_SELECTED";
export const GET_DRINK_DATA = "GET_DRINK_DATA";
export const GET_DRINK_DATA_FAIL = "GET_DRINK_DATA_FAIL";
export const GET_DRINK_DATA_RESET = "GET_DRINK_DATA_RESET";
